create table dbo.BetList
(
    Id                 bigint                                        not null,
    OrderType          varchar(1000),
    BetType            varchar(1000),
    BetTypeDescription varchar(1000),
    BetTypeTemplate    varchar(1000),
    Sport              varchar(1000),
    Placer             varchar(1000),
    WantPrice          decimal(9, 5),
    Price              decimal(9, 5),
    CcyRate            decimal(9, 5),
    PlacementTime      datetimeoffset(0),
    ExpiryTime         datetimeoffset(0),
    Closed             bit,
    CloseReason        varchar(1000),
    Status             varchar(1000),
    TakeStartingPrice  bit,
    KeepOpenIr         bit,
    WantStake          decimal(9, 4),
    Stake              decimal(9, 4),
    ProfitLoss         decimal(9, 4),
    EventId            varchar(1000),
    HomeId             int,
    HomeTeam           varchar(1000),
    AwayId             int,
    AwayTeam           varchar(1000),
    CompetitionId      int,
    CompetitionName    varchar(1000),
    CompetitionCountry varchar(1000),
    StartTime          datetimeoffset(0),
    Date               date,

    CreatedAt          datetimeoffset(0) default sysdatetimeoffset() not null,
    UpdatedAt          datetimeoffset(0) default sysdatetimeoffset() not null,
    constraint PK_BetList primary key (Id),
)

create type BetListType as table
(
    Id                 bigint not null,
    OrderType          varchar(1000),
    BetType            varchar(1000),
    BetTypeDescription varchar(1000),
    BetTypeTemplate    varchar(1000),
    Sport              varchar(1000),
    Placer             varchar(1000),
    WantPrice          decimal(9, 5),
    Price              decimal(9, 5),
    CcyRate            decimal(9, 5),
    PlacementTime      datetimeoffset(0),
    ExpiryTime         datetimeoffset(0),
    Closed             bit,
    CloseReason        varchar(1000),
    Status             varchar(1000),
    TakeStartingPrice  bit,
    KeepOpenIr         bit,
    WantStake          decimal(9, 4),
    Stake              decimal(9, 4),
    ProfitLoss         decimal(9, 4),
    EventId            varchar(1000),
    HomeId             int,
    HomeTeam           varchar(1000),
    AwayId             int,
    AwayTeam           varchar(1000),
    CompetitionId      int,
    CompetitionName    varchar(1000),
    CompetitionCountry varchar(1000),
    StartTime          datetimeoffset(0),
    Date               date,
    primary key (Id)
)