create or alter proc dbo.uspSaveSide @Id bigint,
                                     @SideIndex tinyint,
                                     @SportName varchar(1000),
                                     @SportId int,
                                     @LeagueName varchar(1000),
                                     @LeagueId int,
                                     @Home varchar(1000),
                                     @HomeId int,
                                     @Away varchar(1000),
                                     @AwayId int,
                                     @MarketName varchar(1000),
                                     @MarketId int,
                                     @Price decimal(9, 5),
                                     @Initiator bit,
                                     @Starts datetimeoffset,
                                     @EventId varchar(1000),
                                     @CheckId bigint,
                                     @AccountLogin varchar(1000),
                                     @CheckPrice decimal(9, 5),
                                     @CheckStatus varchar(1000),
                                     @CountLine int,
                                     @CountEvent int,
                                     @AmountEvent int,
                                     @AmountLine int,
                                     @MinBet decimal(9, 4),
                                     @MaxBet decimal(9, 4),
                                     @Balance int,
                                     @Currency decimal(9, 5),
                                     @CheckDone bigint,
                                     @CalcStatus varchar(1000),
                                     @MaxStake decimal(9, 4),
                                     @MinStake decimal(9, 4),
                                     @MaxWin decimal(9, 4),
                                     @Stake decimal(9, 4),
                                     @Win decimal(9, 4),
                                     @IsFirst bit,
                                     @ServiceName varchar(1000)
as
begin
    set nocount on

    MERGE dbo.Side AS t
    USING (select @Id,
                  @SideIndex,
                  @SportName,
                  @SportId,
                  @LeagueName,
                  @LeagueId,
                  @Home,
                  @HomeId,
                  @Away,
                  @AwayId,
                  @MarketName,
                  @MarketId,
                  @Price,
                  @Initiator,
                  @Starts,
                  @EventId,
                  @CheckId,
                  @AccountLogin,
                  @CheckPrice,
                  @CheckStatus,
                  @CountLine,
                  @CountEvent,
                  @AmountEvent,
                  @AmountLine,
                  @MinBet,
                  @MaxBet,
                  @Balance,
                  @Currency,
                  @CheckDone,
                  @CalcStatus,
                  @MaxStake,
                  @MinStake,
                  @MaxWin,
                  @Stake,
                  @Win,
                  @IsFirst,
                  @ServiceName) s (Id,
                                   SideIndex,
                                   SportName,
                                   SportId,
                                   LeagueName,
                                   LeagueId,
                                   Home,
                                   HomeId,
                                   Away,
                                   AwayId,
                                   MarketName,
                                   MarketId,
                                   Price,
                                   Initiator,
                                   Starts,
                                   EventId,
                                   CheckId,
                                   AccountLogin,
                                   CheckPrice,
                                   CheckStatus,
                                   CountLine,
                                   CountEvent,
                                   AmountEvent,
                                   AmountLine,
                                   MinBet,
                                   MaxBet,
                                   Balance,
                                   Currency,
                                   CheckDone,
                                   CalcStatus,
                                   MaxStake,
                                   MinStake,
                                   MaxWin,
                                   Stake,
                                   Win,
                                   IsFirst, ServiceName)
    ON (t.Id = s.Id and t.SideIndex = s.SideIndex)

    WHEN MATCHED THEN
        UPDATE
        SET SportName    = s.SportName,
            SportId      = s.SportId,
            LeagueName   = s.LeagueName,
            LeagueId     = s.LeagueId,
            Home         = s.Home,
            HomeId       = s.HomeId,
            Away         = s.Away,
            AwayId       = s.AwayId,
            MarketName   = s.MarketName,
            MarketId     = s.MarketId,
            Price        = s.Price,
            Initiator    = s.Initiator,
            Starts       = s.Starts,
            EventId      = s.EventId,
            CheckId      = s.CheckId,
            AccountLogin = s.AccountLogin,
            CheckPrice   = s.CheckPrice,
            CheckStatus  = s.CheckStatus,
            CountLine    = s.CountLine,
            CountEvent   = s.CountEvent,
            AmountEvent  = s.AmountEvent,
            AmountLine   = s.AmountLine,
            MinBet       = s.MinBet,
            MaxBet       = s.MaxBet,
            Balance      = s.Balance,
            Currency     = s.Currency,
            CheckDone    = s.CheckDone,
            CalcStatus   = s.CalcStatus,
            MaxStake     = s.MaxStake,
            MinStake     = s.MinStake,
            MaxWin       = s.MaxWin,
            Stake        = s.Stake,
            Win          = s.Win,
            IsFirst      = s.IsFirst,
            ServiceName  = s.ServiceName,
            UpdatedAt    = sysdatetimeoffset()

    WHEN NOT MATCHED THEN
        INSERT (Id,
                SideIndex,
                SportName,
                SportId,
                LeagueName,
                LeagueId,
                Home,
                HomeId,
                Away,
                AwayId,
                MarketName,
                MarketId,
                Price,
                Initiator,
                Starts,
                EventId,
                CheckId,
                AccountLogin,
                CheckPrice,
                CheckStatus,
                CountLine,
                CountEvent,
                AmountEvent,
                AmountLine,
                MinBet,
                MaxBet,
                Balance,
                Currency,
                CheckDone,
                CalcStatus,
                MaxStake,
                MinStake,
                MaxWin,
                Stake,
                Win,
                IsFirst, ServiceName)
        VALUES (s.Id,
                s.SideIndex,
                s.SportName,
                s.SportId,
                s.LeagueName,
                s.LeagueId,
                s.Home,
                s.HomeId,
                s.Away,
                s.AwayId,
                s.MarketName,
                s.MarketId,
                s.Price,
                s.Initiator,
                s.Starts,
                s.EventId,
                s.CheckId,
                s.AccountLogin,
                s.CheckPrice,
                s.CheckStatus,
                s.CountLine,
                s.CountEvent,
                s.AmountEvent,
                s.AmountLine,
                s.MinBet,
                s.MaxBet,
                s.Balance,
                s.Currency,
                s.CheckDone,
                s.CalcStatus,
                s.MaxStake,
                s.MinStake,
                s.MaxWin,
                s.Stake,
                s.Win,
                s.IsFirst,
                s.ServiceName);
end